version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    
  kaddem-backend:
    depends_on:
      - mysqldb
    image: wajdiouaili/kaddem:0.0.7
    restart: always
    ports:
      - "8082:8082"
    stdin_open: true
    tty: true
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true",
            "spring.datasource.username": "root",
            "spring.datasource.password": "",
            "spring.jpa.hibernate.ddl-auto": "update",
            "spring.jpa.show-sql": "true"
          }'
    command: --allow-public-key-retrieval=true
volumes:
  db: